---
name: workflow de test
"on":
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test-html:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération de code
        uses: actions/checkout@v3

      - name: Vérification syntaxe HTML
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: .

      - name: Déploiement vers GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
